version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5675:5672
        - 15675:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-logs:/var/log/rabbitmq/

  sles:
    image: registry.suse.com/suse/sle15:15.4.27.11.31
    # image: opensuse/leap:15.4
    command: ["sleep","infinity"]
    volumes:
      - ./trento-agent:/usr/bin/trento-agent
  
  leap:
    # image: registry.suse.com/suse/sle15:15.4.27.11.31
    image: opensuse/leap:15.4
    command: ["sleep","infinity"]
    volumes:
      - ./trento-agent:/usr/bin/trento-agent

volumes:
  rabbitmq-data:
  rabbitmq-logs: